GI - Grammar Inference: gi::bluefringe Class Reference
gi::bluefringe Class Reference abstract
Class for BlueFringe inference algorithms.
#include <bluefringe.h>
Public Member Functions
bluefringe (const char *path)
virtual ~bluefringe ()
virtual dfa * run (string path)=0
int get_actual_merge ()
int get_heuristic_merge ()
int get_while_count ()
Protected Member Functions
void read_samples (vector< SYMBOL > *&positive, int *dim_positive, vector< SYMBOL > *&negative, int *dim_negative, int *&wp, int *&wn)
dfaEDSM * build_apta (const vector< SYMBOL > *positive, const int dim_positive, const vector< SYMBOL > *negative, const int dim_negative)
void merge (dfaEDSM *dfa1, int q1, int q2)
void fold (dfaEDSM *originale, int q1, int q2)
void promote (dfaEDSM *dfa1, int q)
virtual int merge_heuristic_score (dfaEDSM *dfa1, vector< SYMBOL > *positive, int dim_positive, vector< SYMBOL > *negative, int dim_negative, int *wp, int *wn)=0
virtual double merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states)=0
void nuoviBlu (dfaEDSM *dfa1)
void eliminaStati (dfaEDSM *dfa1)
void set_fringe_size (int r, int b)
void print_fringe_size ()
Protected Attributes
char * path_samples
int dim_alphabet
map< string, int > mapped_alphabet
string * inverse_mapped_alphabet
int num_actual_merge
int num_heuristic_merge_valued
vector< int > fringe_size [2]
int while_count
Detailed Description
Class for BlueFringe inference algorithms.
Class for all the altgorithms which use a BlueFringe Framework.
Definition at line 30 of file bluefringe.h.
Constructor & Destructor Documentation
gi::bluefringe::bluefringe (const char * path)
Instance an object with all the members and methods for EDSM inference process.
Parameters
path It's the path where find positive and negative samples
Definition at line 36 of file bluefringe.cpp.
gi::bluefringe::~bluefringe () virtual
Destroy and EDSM object, freeing the memory.
Definition at line 53 of file bluefringe.cpp.
Member Function Documentation
gi::dfaEDSM * gi::bluefringe::build_apta (const vector< SYMBOL > * positive, const int dim_positive, const vector< SYMBOL > * negative, const int dim_negative) protected
Build an APTA (Augmented Prefix Tree Acceptor) with positive and negative samples, extracted by read_samples().
Parameters
positive
dim_positive
negative
dim_negative
Returns
A pointer to built APTA.
Definition at line 235 of file bluefringe.cpp.
References gi::dfaEDSM::add_blue_state(), gi::dfaEDSM::add_red_state(), gi::dfa::get_ttable(), and ND.
void gi::bluefringe::eliminaStati (dfaEDSM * dfa1) protected
Set the type state to 'DEL' for that states which are unreachable from every other state: fanin=0.
Parameters
dfa1
Definition at line 532 of file bluefringe.cpp.
References DFA_STATE_UNREACHABLE, gi::dfa::get_dim_alphabet(), gi::dfa::get_num_states(), gi::dfa::get_ttable(), gi::dfaEDSM::remove_blue_state(), and gi::dfaEDSM::remove_red_state().
void gi::bluefringe::fold (dfaEDSM * originale, int q1, int q2) protected
Perform a recursive operation of fold, starting from the states to merge, inside "originale" dfa.
Parameters
originale
q1
q2
Definition at line 382 of file bluefringe.cpp.
References DFA_STATE_ACCEPTING, gi::dfa::get_dim_alphabet(), gi::dfa::get_ttable(), and ND.
int gi::bluefringe::get_actual_merge ()
It's a function with statistical finality. Return the number of merges already performed to the actual stage of EDSM process.
Returns
Number of merges already performed to the actual stage of EDSM process.
Definition at line 559 of file bluefringe.cpp.
int gi::bluefringe::get_heuristic_merge ()
It's a function with statistical finality. Return the number of all simulated merges for heuristic evaluation, from first to actual stage.
Returns
Number of all simulated merges for heuristic evaluation to actual stage.
Definition at line 563 of file bluefringe.cpp.
int gi::bluefringe::get_while_count ()
It's a function with statistical finality. Return the number of iteration of EDSM: it's the number of times that EDSM finded that there was already blue states.
Returns
Definition at line 593 of file bluefringe.cpp.
void gi::bluefringe::merge (dfaEDSM * dfa1, int q1, int q2) protected
Perform a merge operation between state q1 and state q2, for DFA dfa1.
Parameters
dfa1
q1
q2
Definition at line 354 of file bluefringe.cpp.
References gi::dfa::get_dim_alphabet(), gi::dfa::get_num_states(), and gi::dfa::get_ttable().
virtual int gi::bluefringe::merge_heuristic_score (dfaEDSM * dfa1, vector< SYMBOL > * positive, int dim_positive, vector< SYMBOL > * negative, int dim_negative, int * wp, int * wn) protected pure virtual
Return a score for a dfa. It's calculated by heuristic emerged during Abbadingo Competition (1998).
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better.
Implemented in gi::blueStar, gi::edsm, and gi::rpni.
virtual double gi::bluefringe::merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states) protected pure virtual
Implemented in gi::blueStar, gi::edsm, and gi::rpni.
void gi::bluefringe::nuoviBlu (dfaEDSM * dfa1) protected
Update the 'dfa1' adding new blue states. Every state, that is achievable from a red state is promoted to blue, unless arrive state is already red.
Parameters
dfa1
Definition at line 510 of file bluefringe.cpp.
References gi::dfaEDSM::add_blue_state(), gi::dfa::get_dim_alphabet(), gi::dfaEDSM::get_num_red_states(), gi::dfaEDSM::get_red_states(), gi::dfa::get_ttable(), gi::dfaEDSM::is_inside_red_states(), and ND.
void gi::bluefringe::print_fringe_size () protected
Print all the snapshots taken, during EDSM process, about the fringe size.
Definition at line 573 of file bluefringe.cpp.
void gi::bluefringe::promote (dfaEDSM * dfa1, int q) protected
Promote the state q, from blue to red state. Delete the state from the blue state list.
Parameters
dfa1
q
Definition at line 488 of file bluefringe.cpp.
References gi::dfaEDSM::add_blue_state(), gi::dfaEDSM::add_red_state(), gi::dfa::get_dim_alphabet(), gi::dfa::get_ttable(), gi::dfaEDSM::is_inside_blue_states(), ND, and gi::dfaEDSM::remove_blue_state().
void gi::bluefringe::read_samples (vector< SYMBOL > *& positive, int * dim_positive, vector< SYMBOL > *& negative, int * dim_negative, int *& wp, int *& wn) protected
Read positive and negative samples, and copy them inside 'positive' and 'negative' vector in parameters.
Parameters
positive
dim_positive
negative
dim_negative
Definition at line 65 of file bluefringe.cpp.
References intTostring(), and stringToint().
virtual dfa* gi::bluefringe::run (string path) pure virtual
Start an EDSM inference process.
Parameters
path It's the base path where create all the output files of EDSM.
Returns
Inferred DFA
Implemented in gi::blueStar, gi::edsm, and gi::rpni.
void gi::bluefringe::set_fringe_size (int r, int b) protected
Set a new record of values that are the fringe size of blue states, and the number of red states. Every time the function is called a new snapshot is taken.
Parameters
r
b
Definition at line 567 of file bluefringe.cpp.
Member Data Documentation
int gi::bluefringe::dim_alphabet protected
Alphabet size (number of symbols)
Definition at line 38 of file bluefringe.h.
vector<int> gi::bluefringe::fringe_size[2] protected
Number of red (0) and blue (1) states
Definition at line 47 of file bluefringe.h.
string* gi::bluefringe::inverse_mapped_alphabet protected
Definition at line 41 of file bluefringe.h.
map<string, int> gi::bluefringe::mapped_alphabet protected
Definition at line 40 of file bluefringe.h.
int gi::bluefringe::num_actual_merge protected
Number of merge actuated by EDSM
Definition at line 45 of file bluefringe.h.
int gi::bluefringe::num_heuristic_merge_valued protected
Number of merge calculetd for evalution of heuristic by EDSM
Definition at line 46 of file bluefringe.h.
char* gi::bluefringe::path_samples protected
Path of example file (training data)
Definition at line 35 of file bluefringe.h.
int gi::bluefringe::while_count protected
Iterations of EDSM
Definition at line 48 of file bluefringe.h.
The documentation for this class was generated from the following files:
bluefringe.h
bluefringe.cpp