GI - Grammar Inference: gi::blueStar Class Reference
gi::blueStar Class Reference
Class for Blue* inference algorithm.
#include <blueStar.h>
Public Member Functions
blueStar (const char *path, double alpha_value, double delta_value)
~blueStar ()
dfa * run (string path)
double get_error_rate_final_dfa ()
Public Member Functions inherited from gi::bluefringe
bluefringe (const char *path)
virtual ~bluefringe ()
int get_actual_merge ()
int get_heuristic_merge ()
int get_while_count ()
Private Member Functions
double merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states)
int merge_heuristic_score (dfaEDSM *dfa1, vector< SYMBOL > *positive, int dim_positive, vector< SYMBOL > *negative, int dim_negative, int *wp, int *wn)
bool is_mergeable (double error_rate_before, double error_rate_after, int dim_strings, double alpha)
Static Private Member Functions
static double error_rate (dfaEDSM *dfa1, vector< SYMBOL > *positive, int dim_positive, vector< SYMBOL > *negative, int dim_negative, int *&wp, int *&wn, const int tot_wp_w, const int tot_wn_w)
Private Attributes
double alpha = 0.01
double delta = 1000
double error_rate_final_dfa
Additional Inherited Members
Protected Member Functions inherited from gi::bluefringe
void read_samples (vector< SYMBOL > *&positive, int *dim_positive, vector< SYMBOL > *&negative, int *dim_negative, int *&wp, int *&wn)
dfaEDSM * build_apta (const vector< SYMBOL > *positive, const int dim_positive, const vector< SYMBOL > *negative, const int dim_negative)
void merge (dfaEDSM *dfa1, int q1, int q2)
void fold (dfaEDSM *originale, int q1, int q2)
void promote (dfaEDSM *dfa1, int q)
void nuoviBlu (dfaEDSM *dfa1)
void eliminaStati (dfaEDSM *dfa1)
void set_fringe_size (int r, int b)
void print_fringe_size ()
Protected Attributes inherited from gi::bluefringe
char * path_samples
int dim_alphabet
map< string, int > mapped_alphabet
string * inverse_mapped_alphabet
int num_actual_merge
int num_heuristic_merge_valued
vector< int > fringe_size [2]
int while_count
Detailed Description
Class for Blue* inference algorithm.
Class for Blue* inference algorithm, with all members and methods for start an inference process.
Definition at line 24 of file blueStar.h.
Constructor & Destructor Documentation
gi::blueStar::blueStar (const char * path, double alpha_value, double delta_value)
Return a score for a dfa. It's calculated by heuristic emerged during Abbadingo Competition (1998).
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better. Instance an object with all the members and methods for EDSM inference process.
Parameters
path It's the path where find positive and negative samples
Definition at line 35 of file blueStar.cpp.
References alpha, and delta.
gi::blueStar::~blueStar ()
Destroy and EDSM object, freeing the memory.
Definition at line 41 of file blueStar.cpp.
Member Function Documentation
double gi::blueStar::error_rate (dfaEDSM * dfa1, vector< SYMBOL > * positive, int dim_positive, vector< SYMBOL > * negative, int dim_negative, int *& wp, int *& wn, const int tot_wp_w, const int tot_wn_w) static private
Return the number of strings, of the Training Set, not recognized from final automaton. Note, that is not a generalization index but an error index, because it's calculated on the training set rather than test set.
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
Definition at line 45 of file blueStar.cpp.
References gi::dfa::membership_query().
double gi::blueStar::get_error_rate_final_dfa ()
Definition at line 548 of file blueStar.cpp.
bool gi::blueStar::is_mergeable (double error_rate_before, double error_rate_after, int dim_strings, double alpha) private
Check if the merge is statisticaly acceptable.
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
Return if a merge is statistically acceptable.
double gi::blueStar::merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states) private virtual
Return a score for a dfa. It's calculated by statistical heuristic of Blue*, minimimazing the ratio between second type error and earn states.
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better. "MINF" value if the merge is not acceptable.
Implements gi::bluefringe.
Definition at line 81 of file blueStar.cpp.
References DMAX, DMINF, and z_alpha_from_u_alpha_two_proportions_test().
int gi::blueStar::merge_heuristic_score (dfaEDSM * dfa1, vector< SYMBOL > * positive, int dim_positive, vector< SYMBOL > * negative, int dim_negative, int * wp, int * wn) inline private virtual
Return a score for a dfa. It's calculated by heuristic emerged during Abbadingo Competition (1998).
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better.
Implements gi::bluefringe.
Definition at line 50 of file blueStar.h.
gi::dfa * gi::blueStar::run (string path) virtual
Start an EDSM inference process.
Parameters
path It's the base path where create all the output files of EDSM.
Returns
Inferred DFA
Implements gi::bluefringe.
Definition at line 138 of file blueStar.cpp.
References DMAX, gi::dfaEDSM::get_actual_num_states(), gi::dfa::get_arrive_state(), gi::dfaEDSM::get_blue_states(), gi::dfaEDSM::get_num_blue_states(), gi::dfaEDSM::get_num_red_states(), gi::dfa::get_num_states(), gi::dfaEDSM::get_red_states(), intTostring(), MINF, gi::dfa::minimize_TF(), ND, gi::dfaEDSM::print_dfa_dot(), gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), STAT_PROMOTION, gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states(), and z_alpha_from_u_alpha_two_proportions_test().
Member Data Documentation
double gi::blueStar::alpha = 0.01 private
Definition at line 28 of file blueStar.h.
Referenced by blueStar().
double gi::blueStar::delta = 1000 private
Definition at line 29 of file blueStar.h.
Referenced by blueStar().
double gi::blueStar::error_rate_final_dfa private
Error rate for the dfa inferred respect to samples
Definition at line 33 of file blueStar.h.
The documentation for this class was generated from the following files:
blueStar.h
blueStar.cpp