GI - Grammar Inference: gi::dfaEDSM Class Reference
gi::dfaEDSM Class Reference
Class dfaEDSM, inherits from class DFA.
#include <dfaEDSM.h>
Public Member Functions
dfaEDSM ()
dfaEDSM (const dfa &d1)
dfaEDSM (const dfaEDSM &d1)
dfaEDSM (const int n_state, const int dim_alf, const string *alf)
dfaEDSM (const int n_state, const int dim_alf, const string *alf, const int s_state)
~dfaEDSM ()
dfa * to_dfa ()
dfaEDSM * to_canonical_dfaEDSM_from_red_states ()
int get_actual_num_states ()
vector< int > * get_blue_states () const
vector< int > * get_red_states () const
void add_blue_state (int blue_state_index)
void add_red_state (int red_state_index)
void remove_blue_state (int blue_state_index)
void remove_red_state (int red_state_index)
int get_num_blue_states ()
int get_num_red_states ()
bool is_inside_blue_states (int blue_state_index)
bool is_inside_red_states (int red_state_index)
void copy_blue_states (vector< int > *new_blue_vector)
void copy_red_states (vector< int > *new_red_states)
void print_dfa_with_color (string title)
void print_dfa_with_color_mapped_alphabet (string title)
void print_dfa_dot (string title, const char *file_path)
void print_dfa_dot_mapped_alphabet (string title, const char *file_path)
Public Member Functions inherited from gi::dfa
dfa ()
dfa (const int n_state, const int dim_alf, const string *alf)
dfa (const int n_state, const int dim_alf, const string *alf, const int s_state)
dfa (const int n_state, const int dim_alf, const string *alf, const int s_state, const int **tt_copy)
dfa (const dfa &d1)
~dfa ()
int get_dim_alphabet ()
string * get_alphabet ()
int get_num_states ()
int get_start_state ()
int get_arrive_state (vector< SYMBOL > dfa_string)
int ** get_ttable ()
int get_ttable (int i, int j)
void set_ttable_entry (int i, int j, int v)
void set_acceptor_state (int state)
void set_rejector_state (int state)
dfa * unionDFA (dfa *dfa_hp)
dfa * minimize_TF ()
double get_complexity ()
void print_dfa_ttable (string title)
void print_dfa_ttable_mapped_alphabet (string title)
void print_dfa_dot (string title, const char *file_path)
void print_dfa_dot_mapped_alphabet (string title, const char *file_path)
bool membership_query (vector< SYMBOL > str)
vector< SYMBOL > equivalence_query (dfa *dfa_hp)
SYMBOL * table_filling ()
vector< int > * equivalent_states_list_from_table (SYMBOL *distincts)
vector< SYMBOL > witness_from_table (SYMBOL *distinct, int start_state_dfa_hp)
Private Attributes
vector< int > * blue_states
vector< int > * red_states
Additional Inherited Members
Static Public Member Functions inherited from gi::dfa
static dfa read_dfa_file (const string file_name)
Protected Member Functions inherited from gi::dfa
void set_ttable (int **ext_ttab)
void set_num_state (int n)
void set_alphabet (const string *alf, const int d_alf)
Protected Attributes inherited from gi::dfa
int ** ttable
int num_states
int start_state
int dim_alphabet
string * alphabet
map< string, SYMBOL > mapped_alphabet
Detailed Description
Class dfaEDSM, inherits from class DFA.
Class for DFA representation inside the EDSM algorithm. It add two vector, used to store whic state are blue and which state are red. With them, it add also all the members for for their management.
Definition at line 13 of file dfaEDSM.h.
Constructor & Destructor Documentation
gi::dfaEDSM::dfaEDSM ()
Red states Make an instance of new dfa, with all members set to null.
Definition at line 9 of file dfaEDSM.cpp.
References blue_states, and red_states.
gi::dfaEDSM::dfaEDSM (const dfa & d1)
Make an instance of dfaEDSM from an object dfa.
Parameters
d1 Object dfa used for make the dfaEDSM object.
Definition at line 29 of file dfaEDSM.cpp.
References blue_states, and red_states.
gi::dfaEDSM::dfaEDSM (const dfaEDSM & d1)
Constructor for make a copy of a dfaEDSM "d1"
Parameters
d1
Definition at line 37 of file dfaEDSM.cpp.
References blue_states, copy_blue_states(), copy_red_states(), get_blue_states(), get_red_states(), and red_states.
gi::dfaEDSM::dfaEDSM (const int n_state, const int dim_alf, const string * alf)
Make an instance of new dfaEDSM. Give possibility to set the start state.
Parameters
n_state Number of states
dim_alf Size of alphabet
alf Alphabet symbols
Definition at line 25 of file dfaEDSM.cpp.
gi::dfaEDSM::dfaEDSM (const int n_state, const int dim_alf, const string * alf, const int s_state)
Make an instance of new dfaEDSM. Give possibility to set the start state.
Parameters
n_state Number of states
dim_alf Size of alphabet
alf Alphabet symbols
s_state Start state
Definition at line 16 of file dfaEDSM.cpp.
References blue_states, and red_states.
gi::dfaEDSM::~dfaEDSM ()
Destroy a DFA object, freeing the memory.
Definition at line 50 of file dfaEDSM.cpp.
Member Function Documentation
void gi::dfaEDSM::add_blue_state (int blue_state_index)
Add a blue state to the Vector of blue state
Parameters
blue_state_index Index of the new blue state
Definition at line 188 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::build_apta(), gi::bluefringe::nuoviBlu(), and gi::bluefringe::promote().
void gi::dfaEDSM::add_red_state (int red_state_index)
Add a red state to the Vector of blue state
Parameters
red_state_index Index of the new red state
Definition at line 195 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::build_apta(), and gi::bluefringe::promote().
void gi::dfaEDSM::copy_blue_states (vector< int > * new_blue_vector)
Copy in the member vector the blue states from an extern vector
Parameters
new_blue_vector Extern vector of blue states
Definition at line 253 of file dfaEDSM.cpp.
Referenced by dfaEDSM().
void gi::dfaEDSM::copy_red_states (vector< int > * new_red_states)
Copy in the member vector the red states from an extern vector
Parameters
new_red_states Extern vector of red states
Definition at line 263 of file dfaEDSM.cpp.
Referenced by dfaEDSM().
int gi::dfaEDSM::get_actual_num_states ()
Definition at line 162 of file dfaEDSM.cpp.
References ND.
Referenced by gi::blueStar::run().
vector< int > * gi::dfaEDSM::get_blue_states () const
Get a pointer to the vector of blue states.
Returns
Pointer to the vector of blue states.
Definition at line 219 of file dfaEDSM.cpp.
Referenced by dfaEDSM(), gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), gi::rpni::run_elapsed_time(), and gi::edsm::run_elapsed_time().
int gi::dfaEDSM::get_num_blue_states ()
Get the number of blue states.
Returns
Number of blue states.
Definition at line 227 of file dfaEDSM.cpp.
Referenced by gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), gi::rpni::run_elapsed_time(), and gi::edsm::run_elapsed_time().
int gi::dfaEDSM::get_num_red_states ()
Get the number of red states.
Returns
Number of red states.
Definition at line 231 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::nuoviBlu(), gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), gi::rpni::run_elapsed_time(), and gi::edsm::run_elapsed_time().
vector< int > * gi::dfaEDSM::get_red_states () const
Get a pointer to the vector of red states.
Returns
Pointer to the vector of red states.
Definition at line 223 of file dfaEDSM.cpp.
Referenced by dfaEDSM(), gi::bluefringe::nuoviBlu(), gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), gi::rpni::run_elapsed_time(), and gi::edsm::run_elapsed_time().
bool gi::dfaEDSM::is_inside_blue_states (int blue_state_index)
Return true if blue_state_index is inside the Vector of blue states
Parameters
blue_state_index Index of blue state to find between the blue states
Returns
True if blue_state_index is inside the Vector of blue states
Definition at line 235 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::promote().
bool gi::dfaEDSM::is_inside_red_states (int red_state_index)
Return true if red_state_index is inside the Vector of red states
Parameters
red_state_index Index of red state to find between the red states
Returns
True if red_state_index is inside the Vector of red states
Definition at line 244 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::nuoviBlu().
void gi::dfaEDSM::print_dfa_dot (string title, const char * file_path)
Print a dot file for the current dfa, with title "title", in the path "file_path", coloring the states.
Parameters
title Title printed before the transition table
file_path Path where make a dot file
Definition at line 377 of file dfaEDSM.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_REJECTING, DFA_STATE_UNREACHABLE, intTostring(), and ND.
Referenced by gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), and gi::edsm::run_elapsed_time().
void gi::dfaEDSM::print_dfa_dot_mapped_alphabet (string title, const char * file_path)
Print a dot file for the current dfa using the alphabet symbols, with title "title", in the path "file_path", coloring the states.
Parameters
title Title printed before the transition table
file_path Path where make a dot file
Definition at line 440 of file dfaEDSM.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_REJECTING, DFA_STATE_UNREACHABLE, intTostring(), and ND.
Referenced by gi::rpni::run(), gi::edsm::run(), and gi::blueStar::run().
void gi::dfaEDSM::print_dfa_with_color (string title)
Print the transition table with the color of the states. Before it, print the "title"
Parameters
title Title printed before the transition table
Definition at line 273 of file dfaEDSM.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_NON_ACCEPTING, DFA_STATE_REJECTING, intTostring(), and ND.
void gi::dfaEDSM::print_dfa_with_color_mapped_alphabet (string title)
Print the transition table with the color of the states, using the alphabet symbol. Before it, print the "title"
Parameters
title Title printed before the transition table
Definition at line 325 of file dfaEDSM.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_NON_ACCEPTING, DFA_STATE_REJECTING, and ND.
void gi::dfaEDSM::remove_blue_state (int blue_state_index)
Remove a state from the blue states.
Parameters
blue_state_index Index of the blue state to remove.
Definition at line 205 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::eliminaStati(), and gi::bluefringe::promote().
void gi::dfaEDSM::remove_red_state (int red_state_index)
Remove a state from the red states.
Parameters
red_state_index Index of the red state to remove.
Definition at line 212 of file dfaEDSM.cpp.
Referenced by gi::bluefringe::eliminaStati().
gi::dfaEDSM * gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states ()
Differently from "to_dfa()" function; it return a dfaEDSM, without unreachable states, adding if necessary a sink state. It adoperate the information about the red states for select the state for final dfa (use the "eliminaStati" for delete pure unreacheable states).
Returns
A pointer to new dfa.
Definition at line 69 of file dfaEDSM.cpp.
References gi::dfa::get_alphabet(), gi::dfa::get_dim_alphabet(), gi::dfa::get_num_states(), gi::dfa::get_ttable(), ND, and gi::dfa::set_ttable_entry().
Referenced by gi::rpni::run(), gi::edsm::run(), gi::blueStar::run(), gi::rpni::run_elapsed_time(), and gi::edsm::run_elapsed_time().
gi::dfa * gi::dfaEDSM::to_dfa ()
Make an instance of dfa from the current dfaEDSM object.
Returns
A pointer to the new dfa.
Definition at line 64 of file dfaEDSM.cpp.
Member Data Documentation
vector<int>* gi::dfaEDSM::blue_states private
Definition at line 17 of file dfaEDSM.h.
Referenced by dfaEDSM().
vector<int>* gi::dfaEDSM::red_states private
Blue states
Definition at line 18 of file dfaEDSM.h.
Referenced by dfaEDSM().
The documentation for this class was generated from the following files:
dfaEDSM.h
dfaEDSM.cpp